# .travis.yml

language: node_js
node_js:
  - "8.6.0"
services:
  - mongodb
  - xvfb
before_install:
  # clone mt-sso
  - "cd .."
  - "git clone --branch=fixTravisTests https://github.com/DanielJKelly/mt-sso.git"
  - "cd mt-sso"
  - "npm i"
  - "npm run test-travis &"
  - "sleep 5"

  # clone vmt
  - "cd .."
  - "git clone --branch=fixTravisTests https://github.com/DanielJKelly/vmt.git"
  - "cd vmt"
  - "npm i"
  - "npm run test-travis &"
  - "sleep 6"
  - "cd ../encompass"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1024x16"
install:
  - npm install
cache:
  directories:
    - "node_modules"
before_script:
  - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - grunt serve-seed & # start server on test port 8082, & to run in background.
  - sleep 6 # give Web server some time to bind to sockets, etc
script:
   - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && grunt tests || grunt travisTests'
  # - grunt apiTests
  # - grunt endToEndTests
sudo: required
addons:
  chrome: stable
