# .travis.yml

language: node_js
node_js:
  - "8.6.0"
services:
  - mongodb
  - xvfb
before_install: ./scripts/travis-before-install.sh fixTravisTests DanielJKelly
install:
  - npm install
cache:
  directories:
    - "node_modules"
    # - "../mt-sso/node_modules"
    # - "../vmt/server/node_modules"
    # - "../vmt/client/node_modules"
before_script: ./scripts/before-tests.sh
script: ./scripts/run-tests.sh
sudo: required
addons:
  # chrome: stable
env:
  - TEST_SUITE=api
  # - TEST_SUITE=e2e
  - TEST_SUITE=e2eProblems
  - TEST_SUITE=e2eAuth
  - TEST_SUITE=e2eMentoring
  - TEST_SUITE=e2eWorkspaces
  # - TEST_SUITE=e2eVmt cant get these to run correctly on travis
  - TEST_SUITE=e2eGeneral