# .travis.yml

language: node_js
node_js:
  - "8.6.0"
services:
  - mongodb
  - xvfb
before_install:
  # clone mt-sso
  - "cd .."
  - "git clone --branch=fixTravisTests https://github.com/DanielJKelly/mt-sso.git"
  - "cd mt-sso && npm i"
  - "npm run test-travis &"
  - "sleep 5"

  # clone vmt
  - "cd .."
  - "git clone --branch=fixTravisTests https://github.com/DanielJKelly/vmt.git"
  - "cd vmt/server"
  - "npm i --only=production"
  # - npm --prefix ../client install ../client
  # - npm run build-production-test
  # - npm run build-enc-test
  - "npm run test-travis &"
  - "sleep 6"
  - "cd ../../encompass"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1024x16"
install:
  - npm install
cache:
  directories:
    - "node_modules"
    # - "../mt-sso/node_modules"
    # - "../vmt/server/node_modules"
    # - "../vmt/client/node_modules"
before_script: ./scripts/before-tests.sh
script: ./scripts/run-tests.sh
sudo: required
addons:
  # chrome: stable
env:
  - TEST_SUITE=api
  # - TEST_SUITE=e2e
  - TEST_SUITE=e2eProblems
  - TEST_SUITE=e2eAuth
  - TEST_SUITE=e2eMentoring
  - TEST_SUITE=e2eWorkspaces
  # - TEST_SUITE=e2eVmt cant get these to run correctly on travis
  - TEST_SUITE=e2eGeneral